### ISSUE TITLE
[Bug] Feeds list doesn't show feeds without entries

### ISSUE THREAD

**Issue by radmen** [facundoolano/feedi#67]
Hey!

Thank you for this project. I plan to test the app in the following days. I love the idea, and hope to use it as my daily driver :)

I imported my old OPML feed (36 entries), but not all of them are listed at `/feeds` page. I don't know Python very well, but based on the query executed in the `feed_list()`, it appears that the feeds without entries won't be listed.

**Comment by facundoolano** [comment]
Thanks, I'll take a look. I may have introduced this on a [recent PR](https://github.com/facundoolano/feedi/pull/66) (you can go back in git history to confirm if you want).

**Comment by facundoolano** [comment]
I can reproduce the problem, working on a fix.

**Comment by facundoolano** [comment]
I just pushed a fix, let me know if it works for you.

**Comment by radmen** [comment]
Works! Thank you 🙌
